# Generated by Django 6.1.1 on 2026-09-12 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ideas', '0002_idea_next_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('STRUCTURE', 'Structure'), ('CHALLENGE', 'Challenge'), ('SUMMARY', 'Summary')], max_length=30)),
                ('input_context', models.TextField()),
                ('result', models.JSONField()),
                ('provider', models.CharField(default='mock', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='ideas.idea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
