# Generated by Django 6.1.1 on 2026-09-13 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aichatsession_aichatmessage'),
        ('ideas', '0002_idea_next_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE_HYPOTHESIS', 'Create hypothesis'), ('CREATE_TASK', 'Create task'), ('CREATE_RESEARCH', 'Create research'), ('UPDATE_IDEA', 'Update idea')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('APPLIED', 'Applied'), ('REJECTED', 'Rejected')], default='PROPOSED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_actions', to='ideas.idea')),
                ('source_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='ai.aianalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
