# Generated by Django 6.1.1 on 2026-10-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_aiaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiaction',
            options={'ordering': ['status', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='aiaction',
            name='source_analysis',
        ),
        migrations.AddField(
            model_name='aiaction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aiaction',
            name='action_type',
            field=models.CharField(choices=[('CREATE_TASK', 'Créer une tâche'), ('CREATE_HYPOTHESIS', 'Créer une hypothèse'), ('ADD_RESEARCH', 'Ajouter une recherche'), ('UPDATE_IDEA', "Mettre à jour l'idée"), ('NEXT_STEP', 'Définir une prochaine étape')], max_length=50),
        ),
        migrations.AlterField(
            model_name='aiaction',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='aiaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('APPLIED', 'Appliquée'), ('DISMISSED', 'Ignorée')], default='PENDING', max_length=20),
        ),
    ]
