# Generated by Django 6.1.1 on 2026-09-10 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('problem', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('target', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('CAPTURED', 'Captured'), ('UNDERSTANDING', 'Understanding'), ('EXPLORING', 'Exploring'), ('RESEARCHING', 'Researching'), ('VALIDATING', 'Validating'), ('BUILDING', 'Building'), ('LAUNCHED', 'Launched'), ('ARCHIVED', 'Archived')], default='CAPTURED', max_length=30)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('capture_type', models.CharField(choices=[('TEXT', 'Text'), ('VOICE', 'Voice'), ('IMPORT', 'Import')], default='TEXT', max_length=20)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('context', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('INBOX', 'Inbox'), ('PROCESSED', 'Processed'), ('DISMISSED', 'Dismissed')], default='INBOX', max_length=20)),
                ('captured_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to=settings.AUTH_USER_MODEL)),
                ('idea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captures', to='ideas.idea')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6366f1', max_length=20)),
                ('ideas', models.ManyToManyField(blank=True, related_name='tags', to='ideas.idea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_tag_per_user')],
            },
        ),
    ]
