# Generated by Django 6.1.1 on 2026-09-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='next_action',
            field=models.TextField(blank=True),
        ),
    ]
